<?php

use think\migration\Seeder;

class AdminMenuSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $menus = [
            [
                'id'         => 1,
                'parent_id'  => 0,
                'name'       => '控制台',
                'icon'       => 'dashboard',
                'path'       => '/dashboard',
                'component'  => 'dashboard/index',
                'permission' => 'dashboard',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 2,
                'parent_id'  => 0,
                'name'       => '用户管理',
                'icon'       => 'user',
                'path'       => '/user',
                'component'  => '',
                'permission' => 'user',
                'menu_type'  => 1,
                'sort'       => 2,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 3,
                'parent_id'  => 2,
                'name'       => '用户列表',
                'icon'       => '',
                'path'       => '/user/list',
                'component'  => 'user/list',
                'permission' => 'user:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 4,
                'parent_id'  => 0,
                'name'       => '商户管理',
                'icon'       => 'shop',
                'path'       => '/merchant',
                'component'  => '',
                'permission' => 'merchant',
                'menu_type'  => 1,
                'sort'       => 3,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 5,
                'parent_id'  => 4,
                'name'       => '商户列表',
                'icon'       => '',
                'path'       => '/merchant/list',
                'component'  => 'merchant/list',
                'permission' => 'merchant:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 6,
                'parent_id'  => 0,
                'name'       => '应用管理',
                'icon'       => 'app',
                'path'       => '/app',
                'component'  => '',
                'permission' => 'app',
                'menu_type'  => 1,
                'sort'       => 4,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 7,
                'parent_id'  => 6,
                'name'       => '应用列表',
                'icon'       => '',
                'path'       => '/app/list',
                'component'  => 'app/list',
                'permission' => 'app:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 8,
                'parent_id'  => 0,
                'name'       => '卡密管理',
                'icon'       => 'key',
                'path'       => '/card',
                'component'  => '',
                'permission' => 'card',
                'menu_type'  => 1,
                'sort'       => 5,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 9,
                'parent_id'  => 8,
                'name'       => '卡密列表',
                'icon'       => '',
                'path'       => '/card/list',
                'component'  => 'card/list',
                'permission' => 'card:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 10,
                'parent_id'  => 8,
                'name'       => '生成卡密',
                'icon'       => '',
                'path'       => '/card/generate',
                'component'  => 'card/generate',
                'permission' => 'card:generate',
                'menu_type'  => 2,
                'sort'       => 2,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 11,
                'parent_id'  => 0,
                'name'       => '订单管理',
                'icon'       => 'order',
                'path'       => '/order',
                'component'  => '',
                'permission' => 'order',
                'menu_type'  => 1,
                'sort'       => 6,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 12,
                'parent_id'  => 11,
                'name'       => '订单列表',
                'icon'       => '',
                'path'       => '/order/list',
                'component'  => 'order/list',
                'permission' => 'order:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 13,
                'parent_id'  => 0,
                'name'       => '套餐管理',
                'icon'       => 'package',
                'path'       => '/package',
                'component'  => '',
                'permission' => 'package',
                'menu_type'  => 1,
                'sort'       => 7,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 14,
                'parent_id'  => 13,
                'name'       => '套餐列表',
                'icon'       => '',
                'path'       => '/package/list',
                'component'  => 'package/list',
                'permission' => 'package:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 15,
                'parent_id'  => 0,
                'name'       => '代理管理',
                'icon'       => 'agent',
                'path'       => '/agent',
                'component'  => '',
                'permission' => 'agent',
                'menu_type'  => 1,
                'sort'       => 8,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 16,
                'parent_id'  => 15,
                'name'       => '代理列表',
                'icon'       => '',
                'path'       => '/agent/list',
                'component'  => 'agent/list',
                'permission' => 'agent:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 17,
                'parent_id'  => 0,
                'name'       => '财务管理',
                'icon'       => 'wallet',
                'path'       => '/finance',
                'component'  => '',
                'permission' => 'finance',
                'menu_type'  => 1,
                'sort'       => 9,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 18,
                'parent_id'  => 17,
                'name'       => '钱包流水',
                'icon'       => '',
                'path'       => '/finance/transactions',
                'component'  => 'finance/transactions',
                'permission' => 'finance:transactions',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 19,
                'parent_id'  => 0,
                'name'       => '系统设置',
                'icon'       => 'setting',
                'path'       => '/system',
                'component'  => '',
                'permission' => 'system',
                'menu_type'  => 1,
                'sort'       => 10,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 20,
                'parent_id'  => 19,
                'name'       => '系统配置',
                'icon'       => '',
                'path'       => '/system/config',
                'component'  => 'system/config',
                'permission' => 'system:config',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 21,
                'parent_id'  => 19,
                'name'       => '菜单管理',
                'icon'       => '',
                'path'       => '/system/menu',
                'component'  => 'system/menu',
                'permission' => 'system:menu',
                'menu_type'  => 2,
                'sort'       => 2,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 22,
                'parent_id'  => 19,
                'name'       => '操作日志',
                'icon'       => '',
                'path'       => '/system/logs',
                'component'  => 'system/logs',
                'permission' => 'system:logs',
                'menu_type'  => 2,
                'sort'       => 3,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 23,
                'parent_id'  => 0,
                'name'       => '内容管理',
                'icon'       => 'content',
                'path'       => '/content',
                'component'  => '',
                'permission' => 'content',
                'menu_type'  => 1,
                'sort'       => 11,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 24,
                'parent_id'  => 23,
                'name'       => '公告管理',
                'icon'       => '',
                'path'       => '/content/announcement',
                'component'  => 'content/announcement',
                'permission' => 'content:announcement',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 25,
                'parent_id'  => 0,
                'name'       => '工单管理',
                'icon'       => 'ticket',
                'path'       => '/ticket',
                'component'  => '',
                'permission' => 'ticket',
                'menu_type'  => 1,
                'sort'       => 12,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 26,
                'parent_id'  => 25,
                'name'       => '工单列表',
                'icon'       => '',
                'path'       => '/ticket/list',
                'component'  => 'ticket/list',
                'permission' => 'ticket:list',
                'menu_type'  => 2,
                'sort'       => 1,
                'visible'    => 1,
                'status'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // 幂等: 按 id upsert (与 UserSeeder 一致, 避免重复执行报 Duplicate entry)
        $this->table('ca_admin_menus')
            ->insert($menus)
            ->onConflict(['id'])
            ->replace()
            ->save();
    }
}
