<?php

use think\migration\Seeder;

class SystemConfigSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $configs = [
            [
                'config_key'   => 'site_name',
                'config_value' => '卡密授权系统',
                'config_type'  => 'string',
                'group_name'   => 'basic',
                'remark'       => '站点名称',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'site_logo',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'basic',
                'remark'       => '站点Logo',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'site_icp',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'basic',
                'remark'       => 'ICP备案号',
                'sort'         => 3,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'register_enable',
                'config_value' => '1',
                'config_type'  => 'bool',
                'group_name'   => 'user',
                'remark'       => '是否开放注册',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'register_default_role',
                'config_value' => '3',
                'config_type'  => 'int',
                'group_name'   => 'user',
                'remark'       => '注册默认角色',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'login_max_fail',
                'config_value' => '5',
                'config_type'  => 'int',
                'group_name'   => 'user',
                'remark'       => '登录最大失败次数',
                'sort'         => 3,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'login_lock_time',
                'config_value' => '1800',
                'config_type'  => 'int',
                'group_name'   => 'user',
                'remark'       => '登录锁定时间（秒）',
                'sort'         => 4,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'card_prefix_default',
                'config_value' => 'CA',
                'config_type'  => 'string',
                'group_name'   => 'card',
                'remark'       => '默认卡密前缀',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'card_length_default',
                'config_value' => '16',
                'config_type'  => 'int',
                'group_name'   => 'card',
                'remark'       => '默认卡密长度',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'card_bind_limit_default',
                'config_value' => '1',
                'config_type'  => 'int',
                'group_name'   => 'card',
                'remark'       => '默认绑定设备数限制',
                'sort'         => 3,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'card_heartbeat_interval',
                'config_value' => '60',
                'config_type'  => 'int',
                'group_name'   => 'card',
                'remark'       => '心跳间隔（秒）',
                'sort'         => 4,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'card_offline_timeout',
                'config_value' => '180',
                'config_type'  => 'int',
                'group_name'   => 'card',
                'remark'       => '离线超时时间（秒）',
                'sort'         => 5,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'pay_alipay_enable',
                'config_value' => '0',
                'config_type'  => 'bool',
                'group_name'   => 'payment',
                'remark'       => '支付宝支付开关',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'pay_wechat_enable',
                'config_value' => '0',
                'config_type'  => 'bool',
                'group_name'   => 'payment',
                'remark'       => '微信支付开关',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'agent_enable',
                'config_value' => '1',
                'config_type'  => 'bool',
                'group_name'   => 'agent',
                'remark'       => '代理系统开关',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'agent_default_commission_rate',
                'config_value' => '0.10',
                'config_type'  => 'string',
                'group_name'   => 'agent',
                'remark'       => '默认佣金比例',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'agent_settle_days',
                'config_value' => '7',
                'config_type'  => 'int',
                'group_name'   => 'agent',
                'remark'       => '佣金结算天数',
                'sort'         => 3,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'api_rate_limit_per_minute',
                'config_value' => '60',
                'config_type'  => 'int',
                'group_name'   => 'api',
                'remark'       => 'API每分钟限流',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'email_smtp_host',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'email',
                'remark'       => 'SMTP服务器地址',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'email_smtp_port',
                'config_value' => '465',
                'config_type'  => 'int',
                'group_name'   => 'email',
                'remark'       => 'SMTP端口',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'email_from',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'email',
                'remark'       => '发件人邮箱',
                'sort'         => 3,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'email_from_name',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'email',
                'remark'       => '发件人名称',
                'sort'         => 4,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'email_username',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'email',
                'remark'       => '邮箱账号',
                'sort'         => 5,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'email_password',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'email',
                'remark'       => '邮箱密码/授权码',
                'sort'         => 6,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_driver',
                'config_value' => 'local',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '存储驱动类型',
                'sort'         => 1,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'upload_max_size',
                'config_value' => '10485760',
                'config_type'  => 'int',
                'group_name'   => 'storage',
                'remark'       => '最大上传大小（字节）',
                'sort'         => 2,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'upload_image_exts',
                'config_value' => 'jpg,jpeg,png,gif,bmp,webp',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '允许上传的图片格式',
                'sort'         => 3,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'upload_file_exts',
                'config_value' => 'zip,rar,7z,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,csv',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '允许上传的文件格式',
                'sort'         => 4,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_local_base_url',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '本地存储基础URL',
                'sort'         => 10,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_oss_access_key_id',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '阿里云OSS AccessKey ID',
                'sort'         => 20,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_oss_access_key_secret',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '阿里云OSS AccessKey Secret',
                'sort'         => 21,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_oss_bucket',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '阿里云OSS Bucket',
                'sort'         => 22,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_oss_endpoint',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '阿里云OSS Endpoint',
                'sort'         => 23,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_oss_region',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '阿里云OSS Region',
                'sort'         => 24,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_cos_secret_id',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '腾讯云COS SecretId',
                'sort'         => 30,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_cos_secret_key',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '腾讯云COS SecretKey',
                'sort'         => 31,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_cos_bucket',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '腾讯云COS Bucket',
                'sort'         => 32,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_cos_region',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '腾讯云COS Region',
                'sort'         => 33,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_qiniu_access_key',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '七牛云AccessKey',
                'sort'         => 40,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_qiniu_secret_key',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '七牛云SecretKey',
                'sort'         => 41,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_qiniu_bucket',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '七牛云Bucket',
                'sort'         => 42,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_qiniu_domain',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => '七牛云访问域名',
                'sort'         => 43,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_minio_endpoint',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => 'MinIO Endpoint',
                'sort'         => 50,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_minio_access_key',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => 'MinIO AccessKey',
                'sort'         => 51,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_minio_secret_key',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => 'MinIO SecretKey',
                'sort'         => 52,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_minio_bucket',
                'config_value' => '',
                'config_type'  => 'string',
                'group_name'   => 'storage',
                'remark'       => 'MinIO Bucket',
                'sort'         => 53,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'config_key'   => 'storage_minio_use_ssl',
                'config_value' => '0',
                'config_type'  => 'bool',
                'group_name'   => 'storage',
                'remark'       => 'MinIO启用SSL',
                'sort'         => 54,
                'status'       => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
        ];

        // 幂等: 按 config_key 唯一索引 upsert (ca_system_configs.uk_config_key)
        // 重复执行不会报 Duplicate entry, 已有配置会被更新为最新值
        $this->table('ca_system_configs')
            ->insert($configs)
            ->onConflict(['config_key'])
            ->replace()
            ->save();
    }
}
