<?php

return [
    'roles' => [
        1 => '超级管理员',
        2 => '运营人员',
        3 => '商户',
        4 => '商户子账号',
        5 => '终端用户',
        6 => '代理商',
    ],

    'permissions' => [
        1 => [
            'dashboard',
            'user',
            'user:list',
            'user:create',
            'user:edit',
            'user:delete',
            'merchant',
            'merchant:list',
            'merchant:create',
            'merchant:edit',
            'merchant:delete',
            'package',
            'package:list',
            'package:create',
            'package:edit',
            'package:delete',
            'app',
            'app:list',
            'app:create',
            'app:edit',
            'app:delete',
            'card',
            'card:list',
            'card:create',
            'card:edit',
            'card:delete',
            'order',
            'order:list',
            'order:detail',
            'wallet',
            'wallet:list',
            'wallet:recharge',
            'agent',
            'agent:list',
            'agent:create',
            'agent:edit',
            'agent:delete',
            'system',
            'system:config',
            'system:log',
            'system:menu',
            'announcement',
            'announcement:list',
            'announcement:create',
            'announcement:edit',
            'announcement:delete',
            'ticket',
            'ticket:list',
            'ticket:detail',
            'ticket:reply',
        ],
        2 => [
            'dashboard',
            'user',
            'user:list',
            'user:create',
            'user:edit',
            'merchant',
            'merchant:list',
            'merchant:edit',
            'app',
            'app:list',
            'card',
            'card:list',
            'order',
            'order:list',
            'order:detail',
            'wallet',
            'wallet:list',
            'wallet:recharge',
            'agent',
            'agent:list',
            'announcement',
            'announcement:list',
            'announcement:create',
            'announcement:edit',
            'ticket',
            'ticket:list',
            'ticket:detail',
            'ticket:reply',
        ],
        3 => [
            'dashboard',
            'package',
            'app',
            'app:list',
            'app:create',
            'app:edit',
            'card',
            'card:list',
            'card:create',
            'card:edit',
            'card:delete',
            'device',
            'device:list',
            'order',
            'order:list',
            'order:detail',
            'wallet',
            'wallet:list',
            'wallet:recharge',
            'subuser',
            'subuser:list',
            'subuser:create',
            'subuser:edit',
            'subuser:delete',
            'profile',
            'profile:edit',
            'ticket',
            'ticket:list',
            'ticket:create',
            'ticket:detail',
            'ticket:reply',
        ],
        4 => [
            'dashboard',
            'app',
            'app:list',
            'card',
            'card:list',
            'card:create',
            'card:edit',
            'device',
            'device:list',
            'order',
            'order:list',
            'order:detail',
            'wallet',
            'wallet:list',
            'profile',
            'profile:edit',
            'ticket',
            'ticket:list',
            'ticket:create',
            'ticket:detail',
            'ticket:reply',
        ],
        5 => [
            'dashboard',
            'card',
            'card:list',
            'device',
            'device:list',
            'profile',
            'profile:edit',
        ],
        6 => [
            'dashboard',
            'merchant',
            'merchant:list',
            'order',
            'order:list',
            'order:detail',
            'wallet',
            'wallet:list',
            'wallet:withdraw',
            'profile',
            'profile:edit',
        ],
    ],

    'menus' => [
        [
            'path' => '/dashboard',
            'name' => 'Dashboard',
            'component' => 'dashboard/index',
            'meta' => [
                'title' => '控制台',
                'icon' => 'Odometer',
                'permission' => 'dashboard',
            ],
            'roles' => [1, 2, 3, 4, 5, 6],
        ],
        [
            'path' => '/user',
            'name' => 'User',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '用户管理',
                'icon' => 'User',
                'permission' => 'user',
            ],
            'roles' => [1, 2],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'UserList',
                    'component' => 'user/list',
                    'meta' => [
                        'title' => '用户列表',
                        'permission' => 'user:list',
                    ],
                    'roles' => [1, 2],
                ],
            ],
        ],
        [
            'path' => '/merchant',
            'name' => 'Merchant',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '商户管理',
                'icon' => 'Shop',
                'permission' => 'merchant',
            ],
            'roles' => [1, 2, 6],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'MerchantList',
                    'component' => 'admin/merchant/index',
                    'meta' => [
                        'title' => '商户列表',
                        'permission' => 'merchant:list',
                    ],
                    'roles' => [1, 2, 6],
                ],
            ],
        ],
        [
            'path' => '/merchant/detail/:id',
            'name' => 'MerchantDetail',
            'component' => 'admin/merchant/detail',
            'meta' => [
                'title' => '商户详情',
                'permission' => 'merchant:list',
                'hidden' => true,
            ],
            'roles' => [1, 2],
        ],
        [
            'path' => '/package',
            'name' => 'Package',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '套餐管理',
                'icon' => 'Present',
                'permission' => 'package',
            ],
            'roles' => [1],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'PackageList',
                    'component' => 'admin/package/index',
                    'meta' => [
                        'title' => '套餐列表',
                        'permission' => 'package:list',
                    ],
                    'roles' => [1],
                ],
            ],
        ],
        [
            'path' => '/app',
            'name' => 'App',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '应用管理',
                'icon' => 'Monitor',
                'permission' => 'app',
            ],
            'roles' => [1, 2],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'AppList',
                    'component' => 'admin/app/index',
                    'meta' => [
                        'title' => '应用列表',
                        'permission' => 'app:list',
                    ],
                    'roles' => [1, 2],
                ],
            ],
        ],
        [
            'path' => '/app/detail/:id',
            'name' => 'AdminAppDetail',
            'component' => 'admin/app/detail',
            'meta' => [
                'title' => '应用详情',
                'permission' => 'app:list',
                'hidden' => true,
            ],
            'roles' => [1, 2],
        ],
        [
            'path' => '/app',
            'name' => 'MerchantApp',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '应用管理',
                'icon' => 'Monitor',
                'permission' => 'app',
            ],
            'roles' => [3, 4],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'MerchantAppList',
                    'component' => 'merchant/app/index',
                    'meta' => [
                        'title' => '应用列表',
                        'permission' => 'app:list',
                    ],
                    'roles' => [3, 4],
                ],
            ],
        ],
        [
            'path' => '/app/detail/:id',
            'name' => 'MerchantAppDetail',
            'component' => 'merchant/app/detail',
            'meta' => [
                'title' => '应用详情',
                'permission' => 'app:list',
                'hidden' => true,
            ],
            'roles' => [3, 4],
        ],
        [
            'path' => '/card',
            'name' => 'Card',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '卡密管理',
                'icon' => 'Key',
                'permission' => 'card',
            ],
            'roles' => [1, 2, 3, 4, 5],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'CardList',
                    'component' => 'card/list',
                    'meta' => [
                        'title' => '卡密列表',
                        'permission' => 'card:list',
                    ],
                    'roles' => [1, 2, 3, 4, 5],
                ],
            ],
        ],
        [
            'path' => '/order',
            'name' => 'Order',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '订单管理',
                'icon' => 'Tickets',
                'permission' => 'order',
            ],
            'roles' => [1, 2, 3, 4, 6],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'OrderList',
                    'component' => 'order/list',
                    'meta' => [
                        'title' => '订单列表',
                        'permission' => 'order:list',
                    ],
                    'roles' => [1, 2, 3, 4, 6],
                ],
            ],
        ],
        [
            'path' => '/package',
            'name' => 'MerchantPackage',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '套餐管理',
                'icon' => 'Present',
                'permission' => 'package',
            ],
            'roles' => [3],
            'children' => [
                [
                    'path' => 'index',
                    'name' => 'MerchantPackageIndex',
                    'component' => 'merchant/package/index',
                    'meta' => [
                        'title' => '我的套餐',
                        'permission' => 'package',
                    ],
                    'roles' => [3],
                ],
            ],
        ],
        [
            'path' => '/wallet',
            'name' => 'Wallet',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '钱包管理',
                'icon' => 'Wallet',
                'permission' => 'wallet',
            ],
            'roles' => [1, 2, 3, 4, 6],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'WalletList',
                    'component' => 'admin/wallet/list',
                    'meta' => [
                        'title' => '钱包列表',
                        'permission' => 'wallet:list',
                    ],
                    'roles' => [1, 2, 6],
                ],
                [
                    'path' => 'index',
                    'name' => 'MerchantWalletIndex',
                    'component' => 'merchant/wallet/index',
                    'meta' => [
                        'title' => '我的钱包',
                        'permission' => 'wallet:list',
                    ],
                    'roles' => [3, 4],
                ],
            ],
        ],
        [
            'path' => '/agent',
            'name' => 'Agent',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '代理管理',
                'icon' => 'Avatar',
                'permission' => 'agent',
            ],
            'roles' => [1, 2],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'AgentList',
                    'component' => 'agent/list',
                    'meta' => [
                        'title' => '代理列表',
                        'permission' => 'agent:list',
                    ],
                    'roles' => [1, 2],
                ],
            ],
        ],
        [
            'path' => '/announcement',
            'name' => 'Announcement',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '公告管理',
                'icon' => 'Bell',
                'permission' => 'announcement',
            ],
            'roles' => [1, 2],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'AnnouncementList',
                    'component' => 'announcement/list',
                    'meta' => [
                        'title' => '公告列表',
                        'permission' => 'announcement:list',
                    ],
                    'roles' => [1, 2],
                ],
            ],
        ],
        [
            'path' => '/ticket',
            'name' => 'Ticket',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '工单管理',
                'icon' => 'Document',
                'permission' => 'ticket',
            ],
            'roles' => [1, 2, 3, 4],
            'children' => [
                [
                    'path' => 'list',
                    'name' => 'TicketList',
                    'component' => 'ticket/list',
                    'meta' => [
                        'title' => '工单列表',
                        'permission' => 'ticket:list',
                    ],
                    'roles' => [1, 2, 3, 4],
                ],
            ],
        ],
        [
            'path' => '/profile',
            'name' => 'Profile',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '个人中心',
                'icon' => 'UserFilled',
                'permission' => 'profile',
            ],
            'roles' => [3, 4, 5, 6],
            'children' => [
                [
                    'path' => 'index',
                    'name' => 'ProfileIndex',
                    'component' => 'merchant/profile/index',
                    'meta' => [
                        'title' => '基本信息',
                        'permission' => 'profile',
                    ],
                    'roles' => [3, 4, 5, 6],
                ],
            ],
        ],
        [
            'path' => '/system',
            'name' => 'System',
            'component' => 'layout/AdminLayout',
            'meta' => [
                'title' => '系统管理',
                'icon' => 'Setting',
                'permission' => 'system',
            ],
            'roles' => [1],
            'children' => [
                [
                    'path' => 'config',
                    'name' => 'SystemConfig',
                    'component' => 'system/config',
                    'meta' => [
                        'title' => '系统配置',
                        'permission' => 'system:config',
                    ],
                    'roles' => [1],
                ],
                [
                    'path' => 'log',
                    'name' => 'SystemLog',
                    'component' => 'system/log',
                    'meta' => [
                        'title' => '操作日志',
                        'permission' => 'system:log',
                    ],
                    'roles' => [1],
                ],
            ],
        ],
    ],

    'whitelist' => [
        'api/admin/auth/login',
        'api/admin/auth/refresh',
        'api/register/merchant',
    ],
];
